apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::959199095557:role/eksctl-eksctl-demo-nodegroup-ng-7-NodeInstanceRole-186FQQHZDDW8O
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::959199095557:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-03T23:03:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1108"
  uid: e65db076-b1fc-4433-99b0-d5f1e2f70ca0